Repository mlee97/SOEN-390-Team5, pull requests merged in 2021-02, with the labels that each got.

#26 docs(issue-25): update README
  README.md
Labels: documentation, priority: medium, risk: low, story point: 1

#28 feat: added database seed for a master user
  ERP/database/seeders/DatabaseSeeder.php
  ERP/database/seeders/MasterUserSeeder.php
Labels: deliverable

#29 feat(issue #25): Update README Information
  README.md
Labels: documentation

#32 chore: add documentation for sprint 1
  Documentation/Basic Testing Plan.pdf
  Documentation/Release Plan Sprint 1.xlsx
  Documentation/Risk Management Plan.pdf
  Documentation/Software Architecture Description Sprint 1.pdf
  Documentation/UI mockups for sprint 2.pdf
  Documentation/User Story Backlog.pdf
Labels: documentation

#56 task(issue-47): add materials pop up window edit
  ERP/resources/views/assembly.blade.php
  ERP/resources/views/components/navbar.blade.php
  ERP/resources/views/inventory.blade.php
  ERP/routes/web.php
Labels: front-end

#61 feat(issue-60): created a ui for the jobs table
  ERP/resources/views/components/navbar.blade.php
  ERP/resources/views/jobs.blade.php
  ERP/routes/web.php
Labels: front-end

#59 task(issue-58): add bike, part and material database
  ERP/app/Http/Controllers/BikeController.php
  ERP/app/Http/Controllers/JobController.php
  ERP/app/Http/Controllers/MaterialController.php
  ERP/app/Http/Controllers/PartController.php
  ERP/app/Models/Bike.php
  ERP/app/Models/Job.php
  ERP/app/Models/Material.php
  ERP/app/Models/Part.php
  ERP/database/migrations/2021_02_18_165108_inventory_bike.php
  ERP/database/migrations/2021_02_23_115333_inventory_part.php
  ERP/database/migrations/2021_02_23_115637_inventory_material.php
  ERP/database/migrations/2021_02_23_160206_create_job.php
  ERP/database/seeders/DatabaseSeeder.php
  ERP/database/seeders/DefaultBikeSeeder.php
  ERP/database/seeders/DefaultJobSeeder.php
  ERP/database/seeders/DefaultMaterialSeeder.php
  ERP/database/seeders/DefaultPartSeeder.php
  ERP/resources/views/inventory.blade.php
  ERP/routes/web.php
Labels: back-end

#62 fix: fixed database seeders #58
  .idea/dataSources.xml
  ERP/artisan
  ERP/database/migrations/2021_02_18_165108_create_bikes_table.php
  ERP/database/migrations/2021_02_23_115333_create_parts_table.php
  ERP/database/migrations/2021_02_23_115637_create_materials_table.php
  ERP/database/migrations/2021_02_23_160206_create_jobs_table.php
Labels: bug

#64 bugfix(issue-63): fix bootstrap version change
  ERP/resources/views/User/create-user.blade.php
  ERP/resources/views/User/user-management.blade.php
Labels: bug

#67 task: adding new jobs to queue with status
  ERP/app/Http/Controllers/JobController.php
  ERP/database/seeders/DefaultJobSeeder.php
  ERP/resources/views/create-job.blade.php
  ERP/resources/views/jobs.blade.php
  ERP/routes/web.php
Labels: task

#68 task(issue-44): display notifications when bikes, parts, or materials are low
  .idea/php-test-framework.xml
  ERP/app/Http/Controllers/BikeController.php
  ERP/app/Http/Controllers/MaterialController.php
  ERP/app/Http/Controllers/PartController.php
  ERP/resources/views/inventory.blade.php
  ERP/routes/web.php
Labels: back-end, task

#71 bug(issue-69): fixed broken edit parts button
  ERP/resources/views/inventory.blade.php
Labels: bug

#72 task(issue-57): add backend to update bicycle completion status
  ERP/app/Http/Controllers/JobController.php
  ERP/resources/views/jobs.blade.php
  ERP/routes/web.php
Labels: back-end

#73 feat(issue-38): Fully Integrate Logging
  .gitignore
  .phpunit.result.cache
  ERP/app/Http/Controllers/BikeController.php
  ERP/app/Http/Controllers/JobController.php
  ERP/app/Http/Controllers/LogController.php
  ERP/app/Http/Controllers/MaterialController.php
  ERP/app/Http/Controllers/PartController.php
  ERP/app/Http/Controllers/UserController.php
  ERP/app/Http/Middleware/ITAccessOnly.php
  ERP/app/Models/Log.php
  ERP/database/migrations/2021_02_12_095859_create_logs_table.php
  ERP/resources/views/Logging/log-page.blade.php
  ERP/resources/views/User/create-user.blade.php
  ERP/resources/views/User/user-management.blade.php
  ERP/resources/views/components/navbar.blade.php
  ERP/resources/views/layouts/master.blade.php
  ERP/routes/web.php
Labels: task

#74 task(issue-43): added delete function to jobs table
  ERP/app/Http/Controllers/JobController.php
  ERP/resources/views/jobs.blade.php
  ERP/routes/web.php
Labels: task

#77 task(issue-76): added new tests for inventory
  ERP/database/factories/UserFactory.php
  ERP/tests/Feature/InventoryTest.php
Labels: task

#78 test (issue-76): added test for auth, user management and job
  ERP/composer.json
  ERP/composer.lock
  ERP/phpunit.xml
  ERP/supervisord.log
  ERP/supervisord.pid
  ERP/tests/Feature/EmailVerificationTest.php
  ERP/tests/Feature/ExampleTest.php
  ERP/tests/Feature/PasswordConfirmationTest.php
  ERP/tests/Feature/PasswordResetTest.php
  ERP/tests/Feature/RegistrationTest.php
  ERP/tests/Unit/AuthenticationTest.php
  ERP/tests/Unit/ExampleTest.php
  ERP/tests/Unit/InventoryTest.php
  ERP/tests/Unit/JobTest.php
  ERP/tests/Unit/LogTest.php
  ERP/tests/Unit/UserTest.php
Labels: task

#81 fix: fixed the excel doc by changing them to pdf
  Documentation/Bug Report Sprint 2.pdf
  Documentation/Bug Report Sprint 2.xlsx
  Documentation/Release Plan + Acceptance Tests Sprint 2 .pdf
  Documentation/Release Plan + Acceptance Tests Sprint 2_.xlsx
  Documentation/Testing Report Sprint 2.xlsx
  Documentation/Testing_Report.pdf
Labels: bug

#82 task: merge develop to master
  Documentation/Bug Report Sprint 2.pdf
  Documentation/Bug Report Sprint 2.xlsx
  Documentation/Release Plan + Acceptance Tests Sprint 2 .pdf
  Documentation/Release Plan + Acceptance Tests Sprint 2_.xlsx
  Documentation/Testing Report Sprint 2.xlsx
  Documentation/Testing_Report.pdf
Labels: task
