Repository mlee97/SOEN-390-Team5, pull requests merged in 2021-03, with the labels that each got.

#85 bug(issue-83): fixed delete button for bikes
  ERP/app/Http/Controllers/BikeController.php
Labels: bug

#86 task(issue-84): added comments for inventory controllers
  ERP/app/Http/Controllers/BikeController.php
  ERP/app/Http/Controllers/MaterialController.php
  ERP/app/Http/Controllers/PartController.php
Labels: task

#115 task(issue-106-107): create an accountant view and populate it with sales table
  ERP/app/Http/Controllers/AccountantController.php
  ERP/resources/views/accountant.blade.php
  ERP/resources/views/components/navbar.blade.php
  ERP/routes/web.php
Labels: front-end, task

#131 task(issue-129): added some default orders to orders table and some default users to users table
  ERP/database/seeders/DatabaseSeeder.php
  ERP/database/seeders/DefaultOrderSeeder.php
  ERP/database/seeders/MasterUserSeeder.php
Labels: task

#128 task(issue-95): create shipping page, populate tables, and update status
  .idea/.name
  ERP/app/Http/Controllers/ShippingController.php
  ERP/app/Http/Kernel.php
  ERP/app/Http/Middleware/ShippingAccessOnly.php
  ERP/resources/views/components/navbar.blade.php
  ERP/resources/views/shipping.blade.php
  ERP/routes/web.php
Labels: task

#134 task(issue-132): add unit tests for shipping
  ERP/tests/Unit/ShippingTest.php
Labels: task

#138 feat(issue-108-109-121-137): create a sales and bike_sale database table to populate the accountant sales view
  ERP/app/Http/Controllers/AccountantController.php
  ERP/app/Http/Controllers/SaleController.php
  ERP/app/Models/Bike.php
  ERP/app/Models/Sale.php
  ERP/database/migrations/2021_03_13_150919_create_sales_table.php
  ERP/database/migrations/2021_03_15_132046_create_bike_sale_table.php
  ERP/database/seeders/Bike_Parts_Material_Order_Sale_Seeder.php
  ERP/database/seeders/DatabaseSeeder.php
  ERP/resources/views/accountant.blade.php
Labels: back-end, front-end

#139 task(issue 133): updated readme file
  README.md
Labels: documentation

#140 feat(issue 119): machine status ui/db
  .vscode/settings.json
  ERP/app/Http/Controllers/JobController.php
  ERP/app/Http/Controllers/MachineController.php
  ERP/app/Models/Machine.php
  ERP/database/migrations/2021_03_12_190303_create_machines_table.php
  ERP/database/seeders/DatabaseSeeder.php
  ERP/database/seeders/DefaultMachineSeeder.php
  ERP/resources/views/User/create-user.blade.php
  ERP/resources/views/components/navbar.blade.php
  ERP/resources/views/jobs.blade.php
  ERP/resources/views/machine-status.blade.php
  ERP/resources/views/welcome.blade.php
  ERP/routes/web.php
Labels: back-end, feature, front-end

#145 Task/issue 133/update readme/kelvin
  README.md
Labels: documentation

#143 Bugfix(issue 141): fix job seeder
  ERP/app/Models/Job.php
  ERP/database/migrations/2021_02_23_160206_create_jobs_table.php
  ERP/database/seeders/DatabaseSeeder.php
  ERP/database/seeders/DefaultJobSeeder.php
  ERP/resources/views/jobs.blade.php
Labels: bug

#148 task(issue-146): add unit tests for machine status
  ERP/app/Http/Kernel.php
  ERP/app/Http/Middleware/ManufacturerAccessOnly.php
  ERP/routes/web.php
  ERP/tests/Unit/ManufacturingTest.php
Labels: feature

#151 bug(issue-149): restrict "Jobs" and "Assembly" to Manufacturer Worker #149
  ERP/resources/views/components/navbar.blade.php
Labels: bug

#152 testing(issue-147): add test to accountant
  ERP/tests/Unit/AccountantTest.php
Labels: testing

#153 task-bugfix(issue-144-150)fix broken tests + add unit testing
  ERP/.gitignore
  ERP/app/Http/Controllers/BikeController.php
  ERP/app/Http/Controllers/JobController.php
  ERP/app/Http/Controllers/MaterialController.php
  ERP/app/Models/Job.php
  ERP/config/session.php
  ERP/tests/Unit/InventoryTest.php
  ERP/tests/Unit/JobTest.php
  ERP/tests/Unit/OrderTest.php
  ERP/tests/Unit/ShippingTest.php
Labels: bug, testing

#156 task(issue-155): added static analysis tool to project
  ERP/composer.json
  ERP/composer.lock
  ERP/phpstan.neon
Labels: task

#157 task(issue-154): added test for parts and materials
  ERP/tests/Unit/InventoryTest.php
Labels: task, testing

#160 Task(issue 133): update readme
  README.md
Labels: documentation

#161 Update README.md
  README.md
Labels: documentation

#142 task(issue-136): Add export button for Sales
  ERP/app/Http/Controllers/SaleController.php
  ERP/resources/views/Logging/log-page.blade.php
  ERP/resources/views/accountant.blade.php
  ERP/resources/views/layouts/master.blade.php
  ERP/routes/web.php
Labels: feature, front-end, task

#165 endofsprint(issue-159): merge develop to main with (added new features) #163
  ERP/app/Http/Controllers/LogController.php
  ERP/composer.json
  ERP/composer.lock
  ERP/config/app.php
  ERP/resources/views/Logging/log-page.blade.php
  ERP/routes/web.php
Labels: end of sprint
