Repository mlee97/SOEN-390-Team5, pull requests merged in 2021-04, with the labels that each got.

#177 bugfix(issue-166-167-175-176): fixed multiple pending bugs
  ERP/app/Http/Controllers/BikeController.php
  ERP/app/Http/Controllers/JobController.php
  ERP/app/Http/Controllers/MaterialController.php
  ERP/app/Http/Controllers/PartController.php
  ERP/app/Models/Job.php
  ERP/database/migrations/2021_02_23_160206_create_jobs_table.php
  ERP/database/migrations/2021_03_15_131721_material_part.php
  ERP/database/migrations/2021_03_15_132046_create_bike_sale_table.php
  ERP/database/migrations/2021_03_15_141027_bike_part.php
  ERP/database/migrations/2021_03_15_152136_material_order.php
  ERP/database/seeders/MasterUserSeeder.php
  ERP/resources/views/User/create-user.blade.php
  ERP/resources/views/User/user-management.blade.php
  ERP/resources/views/components/user-type-dropdown.blade.php
  ERP/resources/views/create-job.blade.php
  ERP/resources/views/inventory.blade.php
  ERP/resources/views/jobs.blade.php
Labels: bug

#168 feat(issue-104): added export button for sales #104
  ERP/app/Http/Controllers/AccountantController.php
  ERP/app/Http/Controllers/LogController.php
  ERP/app/Http/Controllers/SaleController.php
  ERP/resources/views/Logging/log-page.blade.php
  ERP/resources/views/accountant.blade.php
  ERP/routes/web.php
Labels: feature

#195 feat(issue-188): modified inventory page to accommodate the parts that constitute a bicycle
  ERP/app/Http/Controllers/BikeController.php
  ERP/app/Models/Part.php
  ERP/database/migrations/2021_02_23_115333_create_parts_table.php
  ERP/database/seeders/Bike_Parts_Material_Order_Sale_Seeder.php
  ERP/resources/views/inventory.blade.php
Labels: back-end, front-end, task

#194 feat(issue-193): pulled info from DB to populate assembly page
  ERP/app/Http/Controllers/AssemblyController.php
  ERP/resources/views/assembly.blade.php
  ERP/routes/web.php
Labels: back-end, front-end, task

#196 task(issue-192): add orders to accountant view
  ERP/app/Http/Controllers/AccountantController.php
  ERP/resources/views/accountant.blade.php
Labels: back-end, front-end

#199 feat(issue-198/bug-197): specify materials when creating a part
  ERP/app/Http/Controllers/BikeController.php
  ERP/app/Http/Controllers/PartController.php
  ERP/composer.lock
  ERP/resources/views/inventory.blade.php
Labels: back-end, front-end, task

#204 feat(issue-203): create accountant and sales person middleware and seeders
  ERP/app/Http/Kernel.php
  ERP/app/Http/Middleware/AccountantAccessOnly.php
  ERP/app/Http/Middleware/SalesAccessOnly.php
  ERP/database/seeders/MasterUserSeeder.php
  ERP/resources/views/components/navbar.blade.php
  ERP/resources/views/components/user-type-dropdown.blade.php
  ERP/resources/views/welcome.blade.php
  ERP/routes/web.php
Labels: back-end, task

#202 feat(issue-200): edit jobs page for quality
  ERP/app/Http/Controllers/JobController.php
  ERP/app/Models/Job.php
  ERP/database/migrations/2021_02_23_160206_create_jobs_table.php
  ERP/database/seeders/DefaultJobSeeder.php
  ERP/resources/views/create-job.blade.php
  ERP/resources/views/jobs.blade.php
  ERP/routes/web.php
Labels: back-end, deliverable, feature, front-end

#207 feat(issue-201): display parts for specified bikes
  ERP/app/Http/Controllers/JobController.php
  ERP/resources/views/jobs.blade.php
Labels: feature, front-end

#210 feat(issue-200): seperate jobs into categories and allow viewing of parts associated with a job
  ERP/app/Http/Controllers/JobController.php
  ERP/resources/views/jobs.blade.php
Labels: feature

#212 task(issue-209): add logging to all Controllers
  .idea/SOEN-390-Team5.iml
  .idea/php.xml
  ERP/app/Http/Controllers/AccountantController.php
  ERP/app/Http/Controllers/AssemblyController.php
  ERP/app/Http/Controllers/JobController.php
  ERP/app/Http/Controllers/LogController.php
  ERP/app/Http/Controllers/MaterialController.php
  ERP/app/Http/Controllers/OrderController.php
  ERP/app/Http/Controllers/PartController.php
  ERP/app/Http/Controllers/SaleController.php
  ERP/composer.lock
Labels: task

#214 bug(issue-221): fixed edit bike and edit part buttons in inventory
  ERP/app/Http/Controllers/BikeController.php
  ERP/app/Http/Controllers/PartController.php
  ERP/resources/views/inventory.blade.php
Labels: bug

#220 feat(issue-206): added unit tests for assembly and inventory
  ERP/app/Http/Kernel.php
  ERP/app/Http/Middleware/AssemblyAccessOnly.php
  ERP/routes/web.php
  ERP/tests/Unit/AssemblyTest.php
  ERP/tests/Unit/InventoryTest.php
Labels: testing

#222 feat(issue-105): logout after inactivity + encrypt session
  .idea/workspace.xml
  ERP/config/session.php
Labels: user story

#224 feat(issue-206): Fixed unit tests for Jobs, Shipping, and Logs
  ERP/tests/Unit/JobTest.php
  ERP/tests/Unit/LogTest.php
  ERP/tests/Unit/ShippingTest.php
Labels: testing

#225 task(issue-223): made site more mobile-friendly
  ERP/resources/views/Logging/log-page.blade.php
  ERP/resources/views/User/login.blade.php
  ERP/resources/views/User/user-management.blade.php
  ERP/resources/views/accountant.blade.php
  ERP/resources/views/assembly.blade.php
  ERP/resources/views/components/navbar.blade.php
  ERP/resources/views/inventory.blade.php
  ERP/resources/views/jobs.blade.php
  ERP/resources/views/machine-status.blade.php
  ERP/resources/views/sales.blade.php
  ERP/resources/views/shipping.blade.php
Labels: front-end

#226 task: add comments
  ERP/app/Http/Controllers/LogController.php
  ERP/app/Http/Controllers/UserController.php
Labels: refactor

#229 feat(issue-206): added unit tests for Accountants and Sales
  ERP/tests/Unit/AccountantTest.php
  ERP/tests/Unit/InventoryTest.php
  ERP/tests/Unit/SalesWorkerTest.php
Labels: testing

#233 added post mortem
  .idea/dataSources.local.xml
  Documentation/Post-Mortem.pdf
  ERP/app/Http/Controllers/AccountantController.php
  ERP/tests/Unit/AccountantTest.php
Labels: documentation

#235 Update Post Mortem
  Documentation/Post-Mortem.pdf
Labels: documentation

#234 merge develop into main
  .idea/dataSources.local.xml
  Documentation/Post-Mortem.pdf
  ERP/app/Http/Controllers/AccountantController.php
  ERP/tests/Unit/AccountantTest.php
Labels: end of sprint
